SRC = $(shell find . -name *.cpp | grep "/src/" | grep -v "/win/")
OBJ = $(SRC:%.cpp=%.o)
LD_FLAGS = -lfltk -lXext -lXft -lfontconfig -lXinerama -lpthread -ldl -lm -lX11 -lcurl -ltag -lXpm -lsqlite3 -lfltk_images -lpng -lfmodex -lXtst
CC_FLAGS = -O2
TARGET = kissplayer

all: $(TARGET)

$(TARGET): $(OBJ)
	g++ $(LD_FLAGS) $(OBJ) -o $(TARGET)

%.o: %.cpp
	g++ $(CC_FLAGS) -c $< -o $@

clean:
	find . -name '*.o' | xargs rm
